packages:
- "js/custom-proxy"
- "js/deprecation-silencer"
- "js/dialog-holder"
- "js/discourse"
- "js/discourse-i18n"
- "js/discourse-markdown-it"
- "js/discourse-plugins"
- "js/discourse-widget-hbs"
- "js/ember-cli-progress-ci"
- "js/float-kit"
- "js/pretty-text"
- "js/select-kit"
- "js/asset-processor"
- "js/truth-helpers"
