name: Release - handle

on:
  workflow_dispatch:
    inputs:
      sha:
        description: "The commit SHA to prepare the release for"
        required: false
        type: string
  push:
    branches:
      - main
      - release/*
    paths:
      - "lib/version.rb"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    container: discourse/discourse_test:slim
    timeout-minutes: 10

    steps:
      - name: Set working directory owner
        run: chown root:root .

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Bundler cache
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: Setup gems
        run: |
          bundle config --local path vendor/bundle
          bundle config --local deployment true
          bundle config --local without development
          bundle install --jobs 4
          bundle clean

      - name: Maybe cut branch
        id: maybe-cut-branch
        if: github.ref == 'refs/heads/main'
        run: bin/rake release:maybe_cut_branch[${{ inputs.sha || github.sha }}]

      - name: Maybe trigger prepare next version
        if: steps.maybe-cut-branch.outputs.new_branch_name
        run: gh workflow run release-prepare.yml -f new_branch_name=${{ steps.maybe-cut-branch.outputs.new_branch_name }}

      - name: Maybe tag release
        if: startsWith(github.ref, 'refs/heads/release/')
        run: bin/rake release:maybe_tag_release[${{ inputs.sha || github.sha }}]
